# Generated by Django 2.2.12 on 2020-04-02 05:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, max_length=1500, null=True, upload_to='drama/image')),
                ('image_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('id_ime', models.CharField(blank=True, max_length=256, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('biodata', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'casts',
            },
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mdl_id', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, max_length=1500, null=True, upload_to='drama/image')),
                ('image_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('title', models.CharField(default='-', max_length=128)),
                ('native_title', models.CharField(blank=True, max_length=128, null=True)),
                ('english_title', models.CharField(blank=True, max_length=128, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('type', models.PositiveIntegerField(blank=True, choices=[(1, 'TV'), (2, 'Movie')], null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('airing_date', models.CharField(blank=True, max_length=128, null=True)),
                ('rating', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('total_episode', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=128, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dramas',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('genre', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='DramaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
            ],
            options={
                'db_table': 'drama_tags',
            },
        ),
        migrations.CreateModel(
            name='DramaGenere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Genre')),
            ],
            options={
                'db_table': 'drama_genres',
            },
        ),
        migrations.CreateModel(
            name='DramaCast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('cast_as', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Cast')),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
            ],
            options={
                'db_table': 'drama_casts',
            },
        ),
    ]
