# Generated by Django 2.2.12 on 2020-04-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DramaGenere',
            new_name='DramaGenre',
        ),
    ]
