# Generated by Django 2.2.12 on 2020-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0002_auto_20200402_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='mdl_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
