# Generated by Django 2.2.12 on 2020-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0004_auto_20200402_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='network',
            field=models.TextField(blank=True, null=True),
        ),
    ]
