# Generated by Django 2.2.12 on 2020-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0006_dramaseason_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image_binnary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='image_binnary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
