# Generated by Django 2.2.12 on 2020-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0007_auto_20200415_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='image_binnary',
            new_name='image_binary',
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='image_binnary',
            new_name='image_binary',
        ),
    ]
