# Generated by Django 2.2.12 on 2020-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0008_auto_20200415_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='slug',
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
    ]
