# Generated by Django 2.2.12 on 2020-04-16 06:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dramasia', '0009_auto_20200415_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='user/profile')),
                ('biodata', models.TextField(blank=True, null=True)),
                ('gender', models.PositiveIntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserWatching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Sedang ditonton'), (2, 'Selesai ditonton'), (3, 'Menunda'), (4, 'Tidak melanjutkan')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.ProfileUser')),
            ],
            options={
                'db_table': 'user_watching',
            },
        ),
        migrations.CreateModel(
            name='UserPolls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('poll', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.ProfileUser')),
            ],
            options={
                'verbose_name': 'Polling',
                'db_table': 'user_polls',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.ProfileUser')),
            ],
            options={
                'verbose_name': 'Pesan Untuk Developer',
                'db_table': 'user_messages',
            },
        ),
        migrations.CreateModel(
            name='UserDramaScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.ProfileUser')),
            ],
            options={
                'db_table': 'user_anime_scores',
            },
        ),
        migrations.CreateModel(
            name='UserAnimeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.Drama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dramasia.ProfileUser')),
            ],
            options={
                'verbose_name': 'Review From User',
                'db_table': 'user_reviews',
            },
        ),
    ]
