# Generated by Django 2.2.12 on 2020-04-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramasia', '0010_profileuser_useranimereview_userdramascore_usermessage_userpolls_userwatching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnimeReview',
            new_name='UserDramaReview',
        ),
        migrations.AlterModelTable(
            name='userdramascore',
            table='user_drama_scores',
        ),
    ]
